### ISSUE TITLE
Heading dropdown is broken ?

### ISSUE THREAD

**Issue by quentinsimon** [ckeditor/strapi-plugin-ckeditor#28]
When I select a heading value into the dropdown, the choosen value is always incremented by one in the HTML code ...
![image](https://user-images.githubusercontent.com/5383226/207575989-e0b792b0-1c72-4f94-a823-3f947f12ec88.png)

Should it be possible to make Heading 1 --> h1 , Heading 2 --> h2  ...

Thanks

**Comment by Reinmar** [comment]
That stems from [https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#heading-levels.](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#heading-levels.) 

Potentially a wrong decision that we took many years ago. 

Taken that editor's config is hard to change in this custom field so far, I agree we should start from h1 because there are usecases for that.

**Comment by Reinmar** [comment]
Released in 0.0.6.

**Comment by quentinsimon** [comment]
Thanks @Reinmar

**Comment by quentinsimon** [comment]
Hi @Reinmar, when do you plan to publish the 0.0.6 version to npm repo plz ?

**Comment by bartkoelewijnnl** [comment]
@Reinmar Can you publish 0.0.6?
